<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.chen</groupId>
        <artifactId>agent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>agent-core</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <lombok.version>1.18.46</lombok.version>
        <fastjson2.version>2.0.62</fastjson2.version>
        <log4j.version>2.26.0</log4j.version>
    </properties>
    <dependencies>
        <!-- Source: https://mvnrepository.com/artifact/com.alibaba.fastjson2/fastjson2 -->
        <dependency>
            <groupId>com.alibaba.fastjson2</groupId>
            <artifactId>fastjson2</artifactId>
            <version>${fastjson2.version}</version>
            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.projectlombok/lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.chen</groupId>
            <artifactId>agent-spy</artifactId>
            <version>${project.version}</version>
            <scope>provided</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-core -->
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <!-- Source: https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>
                <configuration>
                    <!--                    加了lombok的Data注解后的类 在编译时提示找不到符号-->
                    <!--                    所以这里需要增加lombok的注解处理器(IDE里面的配置不生效？！！)-->
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>${lombok.version}</version>
                        </path>
                    </annotationProcessorPaths>
                    <!--                    <debug>true</debug>-->
                    <!--                    <debuglevel>source,lines,vars</debuglevel>-->
<!--                    <compilerArgs>-->
<!--                        <arg> &#45;&#45;add-exports=java.base/sun.net.www.http=ALL-UNNAMED</arg>-->
<!--                        <arg>&#45;&#45;add-exports=java.base/jdk.internal.reflect=ALL-UNNAMED</arg>-->
<!--                    </compilerArgs>-->
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.5.0</version>
                <executions>
                    <!-- 1. 打包主Agent Jar：排除Spy类，避免和Spy Jar冲突 -->
                    <execution>
                        <id>default-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <archive >
                                <!-- 自动生成 JavaAgent 必须的清单属性 -->
                                <manifestEntries>
                                    <Agent-class>org.chen.App</Agent-class>
                                    <!-- Agent 入口类（全类名） -->
                                    <Premain-Class>org.chen.App</Premain-Class>
                                    <!-- 是否允许重定义类 -->
                                    <Can-Redefine-Classes>true</Can-Redefine-Classes>
                                    <!-- 是否允许重转换类（修改已加载类） -->
                                    <Can-Retransform-Classes>true</Can-Retransform-Classes>
                                    <!-- 是否能使用 native 钩子 -->
                                    <Can-Set-Native-Method-Prefix>true</Can-Set-Native-Method-Prefix>
                                </manifestEntries>
                            </archive>
                        </configuration>
                    </execution>
                </executions>
                <configuration>

                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <appendAssemblyId>true</appendAssemblyId>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                    <archive>
                        <manifestEntries>
                            <Premain-Class>org.chen.App</Premain-Class>
                            <Agent-class>org.chen.App</Agent-class>
                            <Can-Redefine-Classes>true</Can-Redefine-Classes>
                            <Can-Retransform-Classes>true</Can-Retransform-Classes>
                            <Can-Set-Native-Method-Prefix>true</Can-Set-Native-Method-Prefix>
<!--                            <Add-Exports>-->
<!--                                java.base/sun.net.www.http=ALL-UNNAMED-->
<!--                                java.base/jdk.internal.reflect=ALL-UNNAMED-->
<!--                            </Add-Exports>-->
                        </manifestEntries>
                    </archive>

                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <!--                        <phase>package</phase>-->
                        <phase>package</phase><!--临时禁用 <phase>none</phase>-->
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>


            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>3.5.0</version> <!-- 使用特定版本的插件 -->
                <executions>
                    <execution>
                        <id>copy-config</id>
                        <phase>process-resources</phase> <!-- 绑定到 process-resources 阶段 -->
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${out.cracked.dir}</outputDirectory> <!-- 目标目录 -->
                            <resources>
                                <resource>
                                    <directory>src/main/resources</directory> <!-- 源目录 -->
                                    <includes>
                                        <include>config.json</include>
                                        <include>activeCode.txt</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                    <execution>
                        <id>copy-jar</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-resources</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${out.cracked.dir}</outputDirectory> <!-- 目标目录 -->
                            <resources>
                                <resource>
                                    <directory>${project.build.directory}</directory> <!-- 源目录 -->
                                    <includes>
                                        <include>${project.build.finalName}.jar</include>
                                        <include>${project.build.finalName}-jar-with-dependencies.jar</include>
                                    </includes>
                                </resource>
                            </resources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.7.0</version>
                <dependencies>
                    <!-- Source: https://mvnrepository.com/artifact/com.guardsquare/proguard-base -->
                    <dependency>
                        <groupId>com.guardsquare</groupId>
                        <artifactId>proguard-base</artifactId>
                        <version>7.9.1</version>
<!--                        <scope>runtime</scope>-->
                    </dependency>
                    <!-- Source: https://mvnrepository.com/artifact/com.guardsquare/proguard-core -->
                    <dependency>
                        <groupId>com.guardsquare</groupId>
                        <artifactId>proguard-core</artifactId>
                        <version>9.3.2</version>
                        <scope>compile</scope>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <phase>none</phase> <!-- package 在打包阶段自动执行混淆 -->
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>

                    <!-- 指定ProGuard版本，必须和插件版本匹配 -->
<!--                    <proguardVersion>7.9.1</proguardVersion>-->

                    <!-- 输入：Maven打包生成的原始jar -->
                    <injar>${project.build.finalName}-jar-with-dependencies.jar</injar>
                    <!-- 输出：混淆后的jar -->
                    <outjar>${project.build.finalName}.jar</outjar>
                    <!-- 输出目录：target/ -->
                    <outputDirectory>${project.build.directory}</outputDirectory>

                    <!-- 生成映射文件，用于还原混淆后的堆栈 -->
                    <mappingFileName>proguard-mapping.txt</mappingFileName>

                    <!-- JDK9+ 必须配置这个，指向JDK的jmods目录 -->
                    <libs>
                        <lib>${java.home}/jmods</lib>
                    </libs>

                    <!-- 混淆规则：可以内联写，也可以用外部文件 -->
                    <proguardInclude>${project.basedir}/proguard-rules.pro</proguardInclude>

                </configuration>
            </plugin>

        </plugins>
    </build>
</project>